import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createServer } from 'node:http';
import { DesktopGrants, desktopHandler } from '../desktop.js';
test('pairing is one-use, expiring, persisted as hashes, revocable and workspace scoped', async t => {
  const root = await mkdtemp(join(tmpdir(), 'dsh-grants-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  let now = Date.now();
  const file = join(root, 'clients.json'), grants = new DesktopGrants(file, 30, () => now);
  await grants.load();
  const w = { id: 'a', title: 'test', path: root };
  const {ticket} = grants.issue(w, '中文.txt');
  const reply = await grants.exchange(ticket);
  assert.equal(reply.openPath, '中文.txt');
  assert.equal(grants.authorize('Bearer ' + reply.token).workspace, 'a');
  await assert.rejects(grants.exchange(ticket), { status: 401 });
  assert.ok(!(await readFile(file, 'utf8')).includes(reply.token));
  const restarted = new DesktopGrants(file, 30, () => now); await restarted.load();
  assert.equal(restarted.authorize('Bearer ' + reply.token).id, reply.grantId);
  await restarted.revoke(reply.grantId);
  assert.throws(() => restarted.authorize('Bearer ' + reply.token), { status: 401 });
  const stale = grants.issue(w, ''); now += 60001;
  await assert.rejects(grants.exchange(stale.ticket), { status: 401 });
  now += 31 * 86400000;
  assert.throws(() => grants.authorize('Bearer ' + reply.token), { status: 401 });
});
test('native HTTP route requires bearer, fences origin, ignores workspace switching, rejects stale saves', async t => {
  const root = await mkdtemp(join(tmpdir(), 'dsh-bridge-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  await writeFile(join(root, 'a.txt'), 'original');
  const grants = new DesktopGrants(join(root, 'state', 'clients.json'));
  const w = { id: 'a', title: 'test', path: root };
  let current = w;
  const handler = desktopHandler({ connection: { requestRejection: req => req.headers.origin ? 403 : 401 }, workspaceRegistry: { get: id => id === 'a' ? current : undefined } }, { maxFileBytes: 4096, maxEntries: 100 }, grants);
  const server = createServer(handler);
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  t.after(() => new Promise(resolve => { server.closeAllConnections(); server.close(resolve); }));
  const base = 'http://127.0.0.1:' + server.address().port + '/dsh-files-bridge/';
  const exchange = await fetch(base + 'exchange', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(grants.issue(w, '')) });
  const reply = await exchange.json(); assert.equal(exchange.status, 200);
  const headers = { Authorization: 'Bearer ' + reply.token };
  assert.equal((await fetch(base + 'file?path=a.txt')).status, 401);
  assert.equal((await fetch(base + 'file?path=a.txt', { headers: { ...headers, Origin: 'http://evil.invalid' } })).status, 403);
  const before = await (await fetch(base + 'file?workspace=b&path=a.txt', { headers })).json();
  assert.equal(before.content, 'original');
  assert.equal((await fetch(base + 'file?path=..%2Foutside', { headers })).status, 403);
  const stat = await (await fetch(base + 'stat?path=a.txt', { headers })).json();
  assert.equal(stat.type, 1);
  const save = content => fetch(base + 'file', { method: 'PUT', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ path: 'a.txt', content, version: before.version }) });
  assert.equal((await save('desktop')).status, 200);
  assert.equal((await save('stale')).status, 409);
  assert.equal(await readFile(join(root, 'a.txt'), 'utf8'), 'desktop');
  current = { ...w, path: root + '-moved' };
  assert.equal((await fetch(base + 'stat?path=a.txt', { headers })).status, 403);
  await grants.revoke(reply.grantId);
  assert.equal((await fetch(base + 'info', { headers })).status, 401);
});
